{% set name = "cuda-nvvp" %}
{% set version = "12.6.37" %}
{% set cuda_version = "12.6" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvvp/{{ platform }}/cuda_nvvp-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: a81bb02d101e32317c055fd836f3cc4a2450beb69f379ed7802c82ccf4b728a8  # [linux64]
  sha256: 62504d9dbe2eaa61a2cb22d55b66e666e4a16498e4e2477ed0994010ebb13c74  # [win]

build:
  number: 0
  skip: true  # [osx or aarch64 or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - cuda-nvdisasm
    - cuda-nvprof

test:
  commands:
    - test -f $PREFIX/bin/nvvp      # [linux]
    - test -f $PREFIX/libnvvp/nvvp  # [linux]
    - if not exist %LIBRARY_BIN%\nvvp.bat exit 1     # [win]
    - if not exist %PREFIX%\libnvvp\nvvp.exe exit 1  # [win]

about:
  home: https://developer.nvidia.com/nvidia-visual-profiler
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: NVIDIA Visual Profiler to visualize and optimize the performance of your application.
  description: |
    NVIDIA Visual Profiler to visualize and optimize the performance of your
    application.
  doc_url: https://docs.nvidia.com/cuda/profiler-users-guide/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
